[package]
name = "llama-graph-rag"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies]
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
